(function(g){var window=this;var V2=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.Xz(a),kind:a.o,name:a.u,id:a.H,is_servable:a.B,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},W2=function(a){return a.g?a.g.languageCode:a.i},Gpa=function(a,b){var c=new g.Wz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},X2=function(a){if(!Hpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Ipa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Jpa=function(){this.i=[];
this.g=[]},Y2=function(a,b){return b?a.g.concat(a.i):a.g},Z2=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Xa(c,(0,g.x)(b.lr,b))||c.push(b);break;default:c=a.g,g.Xa(c,(0,g.x)(b.lr,b))||c.push(b)}},$2=function(){g.A.call(this);
this.i=new Jpa;this.u=[]},a3=function(a,b,c){$2.call(this,a);
this.g=null;this.u=b.Nu;this.l=c},b3=function(){this.Wa=[]},c3=function(a,b,c,d,e,f){g.A.call(this);
this.H=a;this.o=b;this.u=new b3;this.g=null;this.B=d;this.I=f;this.i=this.l=null;this.R=c;this.A=e||!1;this.D=new g.J(this.ix,1E3,this);g.B(this,this.D);this.F=new g.Us(this);g.B(this,this.F);this.F.K(b,"SEEK_COMPLETE",this.Kx);this.Kx();this.ix()},d3=function(a,b){var c=g.Uv(g.dw(b,a.H,{})),d={format:"RAW",
withCredentials:!0};a.A&&(d.responseType="arraybuffer");a.i=g.Cr(c,d,3,100).then((0,g.x)(a.NK,a));a.l=b;c=a.u;d=a.l.g[0].i;var e=g.ob(c.Wa,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Wa[e-1]&&e<c.Wa.length&&1==c.Wa[e]-d?(g.bb(c.Wa,e),g.bb(c.Wa,e-1)):0<e&&1==d-c.Wa[e-1]?c.Wa[e-1]=d:e<c.Wa.length&&1==c.Wa[e]-d?c.Wa[e]=d:(g.kb(c.Wa,e,0,d),g.kb(c.Wa,e+1,0,d)))},e3=function(a,b){$2.call(this,g.X(b));
this.g=a;this.B=b;this.l=null;this.o=!1;this.A=g.Ez(g.X(this.B))&&!this.g.i},f3=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.BV(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Wz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Kpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},g3=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.BV(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},h3=function(a,b,c,d,e){$2.call(this,e||null);
c=c||g.Jq(a).hl||"";c=c.split("_").join("-");this.o=g.Lq(a,{hl:c});this.l=b;this.A=!!d;this.B={};this.g=null},i3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.qE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},j3=function(a,b,c,d,e){g.qE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},l3=function(a){a=void 0===a?{}:a;
var b="_"+k3++;return new j3(0,0x8000000000000,0,b,a)},n3=function(a,b,c,d,e,f){var k={};
g.Ra(k,b);g.Ra(k,a.params);g.Ra(k,c);var l={};g.Ra(l,b.xb);a.params.xb&&g.Ra(l,a.params.xb);g.Ra(l,c.xb);k.xb=l;g.W.call(this,{C:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.Ee?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{C:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.B=[];this.P=!1;this.o=a;this.Y=this.T=null;this.Ra=e;this.Qa=f;this.D=null;this.Z=.96*e;this.xa=.96*f;this.l=k;this.Ia=c;this.A=this.i["captions-text"];this.Ca=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.X=d/360*16;this.type=0;this.ma=this.X*m3(l);a=new g.$s(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.gG,this);a.subscribe("dragmove",this.fG,this);a.subscribe("dragend",this.eG,this);this.wa=this.na=0;b="";this.l.windowOpacity&&(a=X2(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Lpa[this.l.textAlign]};
this.Ca&&(a["border-radius"]=b?this.ma/8+"px":"");if(this.u=2==this.o.params.Ee||3==this.o.params.Ee)b=this.element,c="vertical-rl",1==this.l.LA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.zh(b,"-o-writing-mode",c),g.zh(b,"-webkit-writing-mode",c),g.zh(b,"writing-mode",c),g.zh(b,"text-orientation","upright"),g.H(b,"ytp-vertical-caption"),3==this.o.params.Ee&&(g.zh(b,"text-orientation",""),g.zh(b,"transform","rotate(180deg)"));g.zh(this.element,a);switch(this.l.Zf){case 0:case 1:case 2:g.H(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.H(this.element,"ytp-caption-window-bottom")}},m3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},o3=function(a,b){var c={},d=b.background?b.background:a.l.xb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.xb.backgroundOpacity;d=X2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ca&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ma/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.X*m3(b)+"px";d=1;e=b.color||a.l.xb.color;if(b.color||null!=b.textOpacity)e=X2(e),d=null==b.textOpacity?a.l.xb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Vu&&(k=e=b.Vu);var l=a.X/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.kr()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.xb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ue&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.gE&&(c.visibility="hidden");1==b.iE&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Gz||g.Hz,3==a.o.params.Ee?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.De||2==b.De||3==b.De||4==b.De||5==b.De)if(g.Gz)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.De){case 4:case 3:c["text-emphasis-position"]="under right";c["webkit-text-emphasis-position"]="under right";break;
case 5:case 2:c["text-emphasis-position"]="over left",c["webkit-text-emphasis-position"]="over left"}return c},p3=function(a){a.D=g.Rd("SPAN");
g.zh(a.D,{display:"block"});g.H(a.D,"caption-visual-line");a.A.appendChild(a.D)},q3=function(a,b){var c=g.Rd("SPAN");
g.zh(c,{display:"inline-block","white-space":"pre-wrap"});g.zh(c,o3(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.zh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.zh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},r3=function(a,b,c){a.P=a.P||!!c;
var d={};g.Ra(d,a.l.xb);g.Ra(d,c||b.g);g.Ra(d,a.Ia.xb);(c=!a.D)&&p3(a);for(var e=a.T&&a.Y&&g.ac(d,a.Y)?a.T:q3(a,d),f=g.Da(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(p3(a),e=q3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Gz||!g.Dh(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.Dh(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),g.Nd?g.zh(e,m,"1em"):
g.zh(e,m,"0.5em")))}a.Y=d;a.T=e;a.B.push(b)},s3=function(){},u3=function(){this.o=this.i=this.mode=this.l=0;
this.u=new t3(this);this.A=new t3(this);this.g=[];this.clear()},Mpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ll:a,
Ml:b,result:0};a=v3[a];b=v3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Ll:a,Ml:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ll:a,Ml:b,result:2};return{Ll:a,Ml:b,result:3}},Npa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,w3(a.u,b,c,d))},Opa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Npa(a,d.Pu,d.Qu,b):1==d.type&&a.l&496&&w3(a.A,d.Pu,d.Qu,b)}a.g.length=0},x3=function(){this.g=0},y3=function(){this.i=this.l=this.g=0},z3=function(){this.timestamp=this.Xd=0},A3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new z3}this.g=this.i=this.row=0;this.style=new x3;this.u=a;this.o=0},B3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Xd){0==c&&(c=m,d=p);n=String.fromCharCode(r.Xd);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Xd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Xd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=p.timestamp,v<=e&&(e=v),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Tpa=function(a,b){switch(a){case 0:return Ppa[(b&127)-32];
case 1:return Qpa[b&15];case 2:return Rpa[b&31];case 3:return Spa[b&31]}return 0},C3=function(a){return a.l[a.row][a.i]},D3=function(a,b,c){2<=b&&1<a.i&&(--a.i,C3(a).Xd=0);
var d=C3(a);d.timestamp=a.u.i+0;d.Xd=Tpa(b,c);32>a.i&&a.i++},E3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].kg(a.l[c+e][f])},F3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},G3=function(a){a.row=0<a.g?a.g:1;
a.i=1;F3(a,0,15)},H3=function(a){this.o=a;
this.u=0;this.style=new x3;this.A=new A3(a);this.B=new A3(a);this.D=new A3(a);this.i=this.A;this.l=this.B;this.g=this.i},I3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:B3(d,c),G3(a.i),G3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(B3(d,c),F3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},J3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},K3=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},t3=function(a){this.i=a;
this.g=new y3;this.u=0;this.l=new H3(a);this.A=new H3(a);this.o=this.l},w3=function(a,b,c,d){a.g.update();
b=Mpa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ll;c=b.Ml;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&D3(a,0,b),c&96&&D3(a,0,c),0!=b&&0!=c&&3==a.style.g&&B3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;E3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));F3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:D3(b.g,0,32);break a;case 48:57==c?(d=b.g,C3(d).Xd=0,32>d.i&&d.i++):D3(b.g,1,c&15)}break;case 2:c&32&&D3(b.g,2,c&31);break;case 3:c&32&&D3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:J3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,C3(d).Xd=0);break;case 36:d=b.g;b=C3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:I3(b,2,d);break;case 38:I3(b,3,d);break;case 39:I3(b,4,d);break;case 40:D3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);G3(d);K3(b);break;case 43:K3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:B3(a,d)}F3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;B3(a,d);E3(a,b,b+1,a.g-1);F3(a,a.row,1)}break;case 46:F3(b.l,0,15);break;case 47:B3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,J3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},L3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.fd){var n=f[1],p=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");r.getAttribute("t");f=g.Rd("RUBY");l=l.textContent;var v=g.Rd("SPAN");v.innerText=l;f.appendChild(v);n.getAttribute("p");v=g.Rd("RP");l=n.textContent;v.innerText=l;f.appendChild(v);k=k[p.getAttribute("p")];l=p.textContent;p=g.Rd("RT");p.innerText=l;f.appendChild(p);l=k.fd;if(10==l||11==l||12==l||13==l||14==l)if(g.zh(p,"text-emphasis","filled circle"),g.zh(p,"webkit-text-emphasis","filled circle"),
k.fd==k.fd==11||13==k.fd)g.zh(p,"webkit-text-emphasis-position","under left"),g.zh(p,"text-emphasis-position","under left");if(4==k.fd||7==k.fd||12==k.fd||14==k.fd)g.zh(f,"ruby-position","over"),g.zh(f,"-webkit-ruby-position","before");else if(5==k.fd||6==k.fd||11==k.fd||13==k.fd)g.zh(f,"ruby-position","under"),g.zh(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Rd("RP");r.innerText=l;f.appendChild(r);return new i3(a,b,e,c,f,d,m)}switch(m.fd){case 9:case 10:m.De=1;break;
case 11:m.De=2;break;case 12:m.De=3;break;case 13:m.De=4;break;case 14:m.De=5}return new i3(a,b,e,c,l.textContent||"",d,m)},M3=function(){g.A.apply(this,arguments)},N3=function(a){M3.call(this);
this.l={};this.F={};this.H={};this.u="_"+k3++;this.A=a;this.D={};this.i=this.g=null;this.B=!0},O3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},P3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},Q3=function(a,b){var c=O3(a,b);
return void 0!=c?c:null},S3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return R3.test(c),c},T3=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.H[d]:a.A);d=Q3(b,"mh");null!=d&&(c.ar=d);d=Q3(b,"ju");null!=d&&(c.textAlign=d);d=Q3(b,"pd");null!=d&&(c.Ee=d);d=Q3(b,"sd");null!=d&&(c.LA=d);d=S3(b,"wfc");null!=d&&(c.windowColor=d);d=O3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},U3=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.F[d]);d=Q3(b,"ap");null!=d&&(c.Zf=d);d=O3(b,"cc");null!=d&&(c.Zl=d);d=O3(b,"ah");null!=d&&(c.Ve=d);d=O3(b,"rc");null!=d&&(c.Ok=d);d=O3(b,"av");null!=d&&(c.Ig=d);return c},V3=function(a,b,c,d){var e={};
g.Ra(e,U3(a,b));g.Ra(e,T3(a,b));d?g.ac(e,a.A)?(d=a.u,e=a.A):d="_"+k3++:d=b.getAttribute("id")||"_"+k3++;a=O3(b,"t")+c;b=O3(b,"d")||0x8000000000000;if(2==e.Ee||3==e.Ee)c=e.Ok,e.Ok=e.Zl,e.Zl=c;return new j3(a,b,0,d,e)},W3=function(a,b,c,d,e,f,k){n3.call(this,a,b,c,d,e,f,k);
this.type=1},X3=function(a,b,c){this.B=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},Y3=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},Z3=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},$3=function(a,b){M3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new u3;this.g.l=1<<this.track},b4=function(a){if(g.Da(a))return!1;
a=new X3(a,8,0);return a4(a)},a4=function(a){if(!(a.g<a.i.byteLength)||1380139777!=Z3(a))return!1;
a.version=Y3(a);if(1<a.version)return!1;Y3(a);Y3(a);Y3(a);return!0},c4=function(a,b,c,d,e,f,k){n3.call(this,a,b,c,d,e,f,k);
g.H(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.ga=0;this.M=NaN;this.ya=0;this.Ea=null;this.ea=new g.J(this.SK,433,this);g.B(this,this.ea)},Upa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},Vpa=function(a){if(isNaN(a.M)){var b=a.l.Zl;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.zh(c,o3(a,a.l.xb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},Wpa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.LA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},d4=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Ok,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(Vpa(a),a.ya,Upa(a,a.A))},Xpa=function(a,b){d4(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ga){var d=0<c&&0==a.ga;b||isNaN(c)||d||(g.H(a.element,"ytp-rollup-mode"),g.Do(a.ea));g.zh(a.A,"transform",Wpa(a,c));a.ga=c}d4(a)},e4=function(){M3.call(this)},f4=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ue=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new i3(b,c,d,e.id,p.nodeValue,f||0<n,g.Xb(l)?void 0:l);m.push(p);var r=e;g.B(r,p);r.g.push(p)}else r={},g.Ra(r,l),f4(a,b,c,d,e,!0,p,r,m)}},g4=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},h4=function(a,b,c,d){d=Object.assign({ar:0},d);
return new j3(a,b,c,"_"+k3++,d)},i4=function(a){g.A.call(this);
this.i=a;this.g=null},l4=function(a){g.mL.call(this,a);
this.l=g.X(a);this.O=a.getVideoData();this.na=g.JK(a);this.M=a;var b=null,c=g.op("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Zo(c));this.aa=b;this.o={xb:{}};this.u={xb:{}};this.F=[];this.R={};this.T={};this.I=!1;this.ea=g.CV(this.O,this.M);this.wa=!!this.O.captionTracks.length;this.xa=!!this.O.pj;this.oa="3"==this.l.l;b=a.app.u;c=!(!b||!b.dl());this.ma=!(!b||!b.Dh());this.A=this.oa&&c&&!this.ea;this.H=!this.A&&this.oa&&this.ma&&this.ea;this.i=this.B=this.D=this.P=this.ga=null;this.Y=
new i4(this.l);g.B(this,this.Y);c=b=this.g=null;this.A||(b=new g.Ao(this.aB,void 0,this),g.B(this,b),c=new g.J(this.uM,2E3,this),g.B(this,c));this.X=b;this.Z=c;this.ca=new g.Us(this);g.B(this,this.ca);this.A||this.ca.K(a,"resize",this.nt);this.ca.K(a,"onPlaybackAudioChange",this.vI);this.ca.K(a,g.tE("captions"),this.mF,this);this.ca.K(a,"crx_captions",this.nF,this);j4(this,k4(this,"display-settings")||{})},m4=function(a){if(1==a.l.fg||1==a.O.fg||"alwayson"==g.cC(a.O,"yt:cc"))return!0;
if(2==a.l.fg){var b=k4(a,"module-enabled");if(null!=b)return!!b}if(a.O.captionTracks.length)var c=a.player.getAudioTrack().rp;return"ON"==c||"on"==g.cC(a.O,"yt:cc")},n4=function(a,b){if(a.g&&(void 0===b||!b)||!a.O.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.om||"FORCED_ON"==c.rp},p4=function(a,b){if(a.i){if(a.B&&a.B.g)return a.B.g;
var c=b;c||(c=a.xa?!1:a.wa?!1:!0);c=Y2(a.i.i,c);for(var d=[a.O.eg,a.l.eg,g.cC(a.O,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(W2(c[f])==d[e])return c[f];return a.B&&a.B.Ip?a.B.Ip:(d=c.find(function(k){return k.isDefault}))?d:c[0]||o4(a)}return null},o4=function(a){return a.B&&a.B.om},q4=function(a){var b=o4(a);
return!!b&&a.g==b},r4=function(a,b){for(var c=a.M.app.u.ha().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},t4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.I=c,a.I&&s4(a,"module-enabled",!!b));a.g=b;n4(a)&&(a.g=o4(a));a.load()},Ypa=function(a,b){var c=a.na.getVideoContentRect(!0).height;
if(!c)return null;var d=a.na.getPlayerSize();switch(null!=b.params.ar?b.params.ar:1<b.g.length?1:0){case 1:return new W3(b,a.o,a.u,c,d.width,d.height,a.l.experiments);case 2:return new c4(b,a.o,a.u,c,d.width,d.height,a.l.experiments);default:return new n3(b,a.o,a.u,c,d.width,d.height,a.l.experiments)}},j4=function(a,b,c){var d=u4.xb;
a.o={};g.Ra(a.o,u4);a.o.xb={};g.Ra(a.o.xb,d);a.u={xb:{}};var e=b.backgroundOverride?a.u:a.o,f=b.background||d.background;R3.test(f);e.xb.background=f;e=b.colorOverride?a.u:a.o;f=b.color||d.color;R3.test(f);e.xb.color=f;e=b.windowColorOverride?a.u:a.o;f=b.windowColor||u4.windowColor;R3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.u:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.xb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.u:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.xb.fontSizeIncrement=f;f=b.fontStyleOverride?a.u:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Ue?3:d.bold?1:d.Ue?2:0);f=f.xb;switch(e){case 1:f.bold=!0;delete f.Ue;break;case 2:delete f.bold;f.Ue=!0;break;case 3:f.bold=!0;f.Ue=!0;break;default:delete f.bold,delete f.Ue}e=b.textOpacityOverride?a.u:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.xb.textOpacity=f;e=b.windowOpacityOverride?a.u:a.o;f=b.windowOpacity;null==f&&(f=u4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.u:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.xb.charEdgeStyle=f;e=b.fontFamilyOverride?a.u:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.xb.fontFamily=f;a.loaded&&a.nt();c&&s4(a,"display-settings",b)},w4=function(a,b){if(b&&!a.D){var c=l3({Ee:0,
lang:"en"});a.D=[c,new i3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.QK(a.player,a.D)}else!b&&a.D&&(v4(a,a.D),a.D=null)},v4=function(a,b){g.SK(a.player,b);
(0,g.y)(b,function(c){g.db(this.F,c)},a);
a.X.Pj()},k4=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},s4=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.LC.prototype.rj=g.ca(13,function(){for(var a=g.Dd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.tX.prototype.rj=g.ca(12,function(){this.g.rj()});
g.LC.prototype.dl=g.ca(11,function(){return!!this.g.textTracks});
g.tX.prototype.dl=g.ca(10,function(){return this.g.dl()});
g.LC.prototype.jj=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.tX.prototype.jj=g.ca(8,function(a){this.g.jj(a)});
g.CC.prototype.Dh=g.ca(7,function(){});
g.LC.prototype.Dh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.tX.prototype.Dh=g.ca(5,function(){return this.g.Dh()});
g.Wz.prototype.lr=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Tt.prototype.Bm=g.ca(2,function(a){return(a=this.og(a))?a.i:0});
g.Pw.prototype.Bm=g.ca(1,function(){return 0});
var Zpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Ipa=/#(.)(.)(.)/,Hpa=/^#(?:[0-9a-f]{3}){1,2}$/i,R3=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t($2,g.A);$2.prototype.Gz=function(){return!1};
$2.prototype.U=function(){this.Jg();g.A.prototype.U.call(this)};
g.t(a3,$2);a3.prototype.Yq=function(a,b,c){b=this.Mj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Jg();this.g=g.br(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
a3.prototype.Zq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())Z2(this.i,c.value);a()};
a3.prototype.Mj=function(a,b){var c=a.F,d={fmt:b};a.g&&(d.tlang=W2(a));return g.Lq(c,d)};
a3.prototype.Jg=function(){this.g&&this.g.abort()};
b3.prototype.contains=function(a){a=g.ob(this.Wa,a);return 0<=a||0>a&&1==(-a-1)%2};
b3.prototype.length=function(){return this.Wa.length/2};
g.t(c3,g.A);g.h=c3.prototype;g.h.U=function(){g.A.prototype.U.call(this);this.i&&this.i.cancel()};
g.h.Kx=function(){var a=this.o.getCurrentTime();a-=this.o.Hb();var b=this.g;this.g=g.Va(this.R.Af(a).g);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.u=new b3;this.i&&(this.i.cancel(),this.i=null)};
g.h.ix=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Mf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.ri(a),a.g[0].duration&&(this.u.contains(a.g[0].i)||d3(this,a),this.g=g.Va(a.g)));this.D.start()};
g.h.NK=function(a){var b=!(this.A?a.response:a.responseText)||400<=a.status,c=g.Ww(a);c?(a=g.dw(this.l,this.H,{}),b=this.l,g.Zv(b.i,a,c),b.requestId=a.get("req_id"),d3(this,this.l)):(b||null===this.B||(c=this.l.g[0],this.A?this.B(a.response,1E3*(c.startTime+this.o.Hb())):this.B(a.responseText,1E3*(c.startTime+this.o.Hb()))),this.i=this.l=null)};
g.t(e3,$2);g.h=e3.prototype;g.h.Yq=function(a,b,c){this.Jg();b=Kpa(this,a.getId());b||(b=a.i,b=this.g.i?g3(this,b,"386"):g3(this,b));if(b){var d=1E3*(b.index.Bm(b.index.ue())-b.index.Kc(b.index.ue()));this.l=new c3(new g.uv,this.B,b,function(e,f){c(e,a,f,d)},this.A||g.nv(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Gz=function(){var a=this.o;this.o=!1;return a};
g.h.Zq=function(a){var b;this.A?b=[new g.Wz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Wz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?f3(this,"386"):f3(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())Z2(this.i,c.value);a()};
g.h.Jg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Mj=function(){return""};
g.t(h3,$2);h3.prototype.Yq=function(a,b,c){b=this.Mj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Jg();this.g=g.br(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
h3.prototype.Zq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.Lq(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),v="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
Z2(this.i,new g.Wz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:v,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.Jg();this.g=g.br(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
h3.prototype.Mj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=W2(a));return c=g.Lq(c,d)};
h3.prototype.Jg=function(){this.g&&this.g.abort()};var Lpa=["left","right","center","justify"];var u4={windowColor:"#080808",windowOpacity:0,textAlign:2,Zf:7,Ve:50,Ig:100,xb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(i3,g.qE);i3.prototype.toString=function(){return g.qE.prototype.toString.call(this)};g.t(j3,g.qE);j3.prototype.toString=function(){return g.qE.prototype.toString.call(this)};
var k3=0;g.t(n3,g.W);g.h=n3.prototype;g.h.gG=function(a,b){var c=g.Ph(this.element,this.element.parentElement);this.na=a-c.x;this.wa=b-c.y;g.H(this.element,"ytp-dragging")};
g.h.fG=function(a,b){var c=g.Sh(this.element),d=a-this.na-.02*this.Ra,e=b-this.wa-.02*this.Qa,f=(d+c.width/2)/this.Z*3;f=Math.floor(g.pd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.pd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.Z;d=100*g.pd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.pd(c,0,1);this.o.params.Zf=l;this.o.params.Ig=c;this.o.params.Ve=d;this.l.Zf=l;this.l.Ig=c;this.l.Ve=d;this.eA()};
g.h.eG=function(){g.qo(this.element,"ytp-dragging")};
g.h.eA=function(){this.Ah(this.B)};
g.h.Ah=function(a){var b=Math.min(this.Xv(),this.Z),c=this.Wv(),d="";3==this.o.params.Ee&&(d="rotate(180deg)");g.zh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Ve+2;d=this.l.Zf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Ig+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.zh(this.element,a)};
g.h.gp=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.P||this.B.length>b)b=0,this.P=!1,this.B=[],this.D=this.Y=this.T=null,g.Ud(this.A);for(;b<a.length;b++)r3(this,a[b])};
g.h.Xv=function(){return 0};
g.h.Wv=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};s3.prototype.u=function(){};u3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
u3.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var v3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];x3.prototype.set=function(a){this.g=a};
x3.prototype.get=function(){return this.g};
y3.prototype.clear=function(){this.g=0};
y3.prototype.update=function(){this.g=2==this.g?1:0};
y3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
z3.prototype.kg=function(a){this.Xd=a.Xd;this.timestamp=a.timestamp};
z3.prototype.reset=function(){this.timestamp=this.Xd=0};
A3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
A3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Xd?a+"_":a+String.fromCharCode(d.Xd)}a+="\n"}return a};
A3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Ppa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Qpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Rpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Spa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];H3.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.B.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
t3.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(M3,g.A);M3.prototype.reset=function(){};g.t(N3,M3);N3.prototype.reset=function(){this.D={};this.i=this.g=null;this.B=!0};
N3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Ra(l,this.l[m]);m=P3(c,"b");null!=m&&(l.bold=
m);m=P3(c,"i");null!=m&&(l.Ue=m);m=P3(c,"u");null!=m&&(l.underline=m);m=Q3(c,"et");null!=m&&(l.charEdgeStyle=m);m=Q3(c,"of");null!=m&&(l.offset=m);m=S3(c,"bc");null!=m&&(l.background=m);m=S3(c,"ec");null!=m&&(l.Vu=m);m=S3(c,"fc");null!=m&&(l.color=m);m=Q3(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=O3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=O3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=O3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=Q3(c,"rb");null!=m&&10!=m&&(l.fd=10<m?m-1:m);m=Q3(c,
"hg");null!=m&&(l.iE=m);c=Q3(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.De=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=T3(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=U3(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=V3(this,d,e,!1);g.B(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.u;m=!!P3(d,"a");n=(O3(d,"t")||0)+n;var p=O3(d,"d")||5E3;m||(!this.B&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,v=this.l[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.B=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var F=z[C],E=void 0;0<C&&(m=!0);var K=void 0;1==F.nodeType&&(K=F);if(K&&"s"==K.tagName){if((F=this.l[K.getAttribute("p")])&&F.fd&&(1==F.fd?(F=z.slice(C,
C+4),4==F.length&&(E=L3(n,p,l,m,r,F,this.l),C+=3)):E=L3(n,p,l,m,r,[K],this.l)),!E){var R=K;E=n;K=p;F=l;var V=m,ta=r,cb=R.textContent?R.textContent:"",ue=this.l[R.getAttribute("p")];R=O3(R,"t")||0;E=new i3(E+R,K-R,ta,F,cb,V,ue)}}else E=new i3(n,p,r,l,F.textContent||"",m,v);k.push(E);this.i=E}if(0<k.length)for(k[0].windowId==this.u&&(this.g=V3(this,d,e,!0),g.B(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.B(l,k),l.g.push(k),c.push(k)}e=
c}else e=[];return e};g.t(W3,n3);W3.prototype.gp=function(a){var b=this.o.g;n3.prototype.gp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Ra(d,c.g);g.Ra(d,$pa);var e=c.g;var f=d}r3(this,c,d)}};
var $pa={gE:!0};g.t(X3,s3);X3.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+k3++;c=c/1E3-this.B;d=d/1E3-this.B;a=new j3(c,d-c,5,f,{textAlign:0,Zf:0,Ve:2.5*b,Ig:5.33*a});e=new i3(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t($3,M3);$3.prototype.o=function(a){a=new X3(a,a.byteLength,this.i);if(a4(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=Z3(a)*(1E3/45):1==a.version&&(a.o=4294967296*Z3(a)+Z3(a)),a.A=Y3(a);0<a.A;a.A--){var b=Y3(a),c=Y3(a),d=Y3(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Pu:c,Qu:d,order:b.g.length}))}Opa(this.g,a);return a.l}return[]};
$3.prototype.reset=function(){this.g.clear()};g.t(c4,n3);g.h=c4.prototype;g.h.eA=function(){g.Eo(this.ea)};
g.h.SK=function(){g.qo(this.element,"ytp-rollup-mode");this.Ah(this.Ea,!0)};
g.h.Wv=function(){return this.u?this.I:this.H};
g.h.Xv=function(){return this.u?this.H:this.I};
g.h.Ah=function(a,b){this.Ea=a;if(this.o.params.Ok){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;n3.prototype.Ah.call(this,a);Xpa(this,b);n3.prototype.Ah.call(this,a)}else n3.prototype.Ah.call(this,a)};g.t(e4,M3);
e4.prototype.o=function(a,b){for(var c=[],d=a.split(aqa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!bqa.test(f)){var l=x4.exec(f);if(l&&4<=l.length){var m=g4(l[1]),n=g4(l[2])-m;m+=k;var p,r=p=void 0,v=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.q(C?C.split(" "):[]);for(var F=C.next();!F.done;F=C.next())if(F=F.value.split(":"),2==F.length){var E=F[1];switch(F[0]){case "line":F=E.split(",");F[0].endsWith("%")&&(z=F[0],l.Ig=Number.parseInt(z,10),2==F.length&&(v=F[1].trim()));break;case "position":F=E.split(",");
r=F[0];l.Ve=Number.parseInt(r,10);2==F.length&&(p=F[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Ig=100,v||(v="end"));if(!r)switch(l.textAlign){case 0:l.Ve=0;break;case 1:l.Ve=100;break;default:l.Ve=50}r=0;switch(v){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Zf=0>r||8<r?7:r;p=l;f=f.substring(x4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=h4(m,n,5,r),n=new i3(m,n,5,k.id,p,!1,g.Xb(f)?void 0:f),c.push(k),c.push(n),g.B(k,n),k.g.push(n);else for(v=p.split(cqa),1==v.length?(p=5,r=h4(m,n,p,r)):(z=p=6,r=Object.assign({Zl:32},r),r=new j3(m,n,z,"_"+k3++,r)),c.push(r),z=m,l=0;l<v.length;l++)C=v[l],0==l%2?(F=g.so("<html>"+C+"</html>"),F.getElementsByTagName("parsererror").length?
(E=F.createElement("span"),E.appendChild(F.createTextNode(C))):E=F.firstChild,f4(this,z,n-(z-m),p,r,0<l,E,f,c)):z=g4(C)+k}x4.lastIndex=0}}return c};
var bqa=/^NOTE/,aqa=/(?:\r\n|\r|\n){2,}/,x4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),cqa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(i4,g.A);i4.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
i4.prototype.reset=function(){this.g&&this.g.reset()};
i4.prototype.U=function(){this.clear();g.A.prototype.U.call(this)};g.t(l4,g.mL);g.h=l4.prototype;g.h.U=function(){if(this.A||this.H){var a=this.M.app.u;a&&a.rj()}else w4(this,!1);g.mL.prototype.U.call(this)};
g.h.Uk=function(){return this.oa?this.A||this.H:n4(this)?!0:m4(this)};
g.h.load=function(){g.mL.prototype.load.call(this);var a=!g.O(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.B=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.A?r4(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Yq(this.g,"srv3",(0,g.x)(this.AL,this)),!a||this.A||this.H||q4(this)||this.player.la("captionschanged",V2(this.g))),a||(this.g&&!q4(this)?this.player.la("captionschanged",V2(this.g)):this.player.la("onCaptionsTrackListChanged"));else{var b;
this.ea?b=new e3(this.O.ia,this.player):this.wa?b=new a3(this.l,this.O,this.player.getAudioTrack()):b=new h3(this.O.pj,this.O.videoId,this.O.eg||this.l.eg||g.cC(this.O,"yt:cc_default_lang")||this.l.Yb,this.O.pp,this.l);this.i=b;g.B(this,this.i);b.Zq((0,g.x)(this.zL,this))}};
g.h.unload=function(){this.A&&this.g?r4(this,!1):(this.Z&&g.Fo(this.Z),g.TK(this.player,"captions"),this.F=[],this.i&&this.i.Jg(),this.Y.clear(),this.D&&g.QK(this.player,this.D),this.nt());g.mL.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.wI(a.u);this.player.la("captionschanged",{})};
g.h.zL=function(){var a;this.I||m4(this)?a=p4(this,this.I):n4(this)&&(a=o4(this));if(this.A||this.H){for(var b=Y2(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.Xz(e),srclang:W2(e),id:e.toString()};this.H||(f.src=this.i.Mj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}a=this.M.app.u;a.jj(c);c=a.ha();this.ma&&this.ca.K(c.textTracks,"change",this.BL)}else!this.g&&a&&t4(this,a),this.player.la("onCaptionsTrackListChanged"),this.player.la("onApiChange")};
g.h.BL=function(){for(var a=this.M.app.u.ha().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=Y2(this.i.i,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.g:null)!=b&&t4(this,b,!0)};
g.h.eN=function(){!this.g&&this.A||this.unload()};
g.h.AL=function(a,b,c,d){if(a){this.i.Gz()&&(this.F=[],g.TK(this.M,"captions"),this.X.Pj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if(!g.Da(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.lu(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!b4(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.Da(a)){if("WEBVTT"==a.substring(0,6)){b=a;var v=c;e.g||(e.g=new e4);var z=e.g.o(b,v);.01>Math.random()&&g.$p(Error("Deprecated subtitles format in web player: WebVTT"));var C=z}else b:{z=a;v=g.so(z);if(!v||!v.firstChild){var F=Error("Invalid caption track data");
F.params=z;throw F;}if("timedtext"==v.firstChild.tagName){if(3==parseInt(v.firstChild.getAttribute("format"),10)){if(!e.g){z={};var E=W2(b);E&&(z.lang=E,Zpa.test(E)&&(z.Ee=1));e.g=new N3(z,e.i)}C=e.g.o(v,c);break b}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=z;throw K;}if("transcript"==v.firstChild.tagName){var R=Error("Unsupported subtitles format in web player (Format1)");R.params=z;throw R;}var V=Error("Invalid caption track data");V.params=z;throw V;}var ta=C}else{C=
a;v=c;E=d;if(!b4(C))throw Error("Invalid binary caption track data");e.g||(e.g=new $3(E,b));ta=e.g.o(C,v)}var cb=ta}catch(ue){g.L(ue),e.clear(),cb=[]}else cb=[];g.QK(this.player,cb);!this.I||this.H||q4(this)||g.uz(this.l)||g.vz(this.l)||(g.Fo(this.Z),cb=l3({Zf:0,Ve:5,Ig:5,Ok:2,textAlign:0,Ee:0,lang:"en"}),this.P=[cb],e=["Click "," for settings"],this.ga||(ta=new g.nD(g.rQ()),g.B(this,ta),this.ga=ta.element),ta=cb.end-cb.start,(b=g.Xz(this.g))&&this.P.push(new i3(cb.start,ta,0,cb.id,b)),this.P.push(new i3(cb.start,
ta,0,cb.id,e[0]),new i3(cb.start,ta,0,cb.id,this.ga,!0),new i3(cb.start,ta,0,cb.id,e[1],!0)),g.QK(this.player,this.P),g.Do(this.Z));!this.I||this.H||q4(this)||(s4(this,"module-enabled",!0),this.B&&(this.B.g=this.g),(cb=g.U(this.player.app))&&g.wI(cb.u));this.I=!1}};
g.h.mF=function(a){this.F.push(a);this.X.Pj()};
g.h.nF=function(a){g.db(this.F,a);this.i instanceof e3&&this.i.A&&g.SK(this.player,[a]);this.X.Pj()};
g.h.oM=function(a){if(a instanceof j3){var b=this.R[a.id];b&&b.o!=a&&(b.dispose(),delete this.R[a.id],b=null);b||(b=Ypa(this,a))&&(this.R[a.id]=b)}else b=a.windowId,this.T[b]||(this.T[b]=[]),this.T[b].push(a)};
g.h.uM=function(){v4(this,this.P);this.P=null};
g.h.aB=function(){this.X.stop();g.Yb(this.T);this.F.sort(g.sE);var a=this.F;if(this.D){var b=(0,g.Xd)(a,function(c){return-1==this.D.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.oM,this);g.Kb(this.R,function(c,d){this.T[d]?(c.element.parentNode||g.XK(this.player,c.element,4),c.Ah(this.T[d])):(c.dispose(),delete this.R[d])},this)};
g.h.zM=function(){j4(this,{},!0);g.O(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.la("captionssettingschanged")};
g.h.xD=function(){var a=u4.xb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ue?3:a.bold?1:a.Ue?2:0,textOpacity:a.textOpacity,windowColor:u4.windowColor,windowOpacity:u4.windowOpacity};var b=k4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.gB=function(a,b){var c={};g.Ra(c,k4(this,"display-settings"));g.Ra(c,a);j4(this,c,b);this.player.la("captionssettingschanged")};
g.h.nt=function(){!this.A&&this.loaded&&(g.Kb(this.R,function(a,b){a.dispose();delete this.R[b]},this),this.aB())};
g.h.zc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.pd(b,-2,4);this.gB({fontSizeIncrement:c});return c;case "reload":b&&!this.A&&t4(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.vb&&s4(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.A)break;if(!g.Na(b))break;if(g.Xb(b)){t4(this,null,!0);break}for(var d=Y2(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Gpa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||t4(this,c,!0)}else return this.loaded&&this.g&&!q4(this)?V2(this.g):{};return"";case "tracklist":return this.i?(0,g.ge)(Y2(this.i.i,!(!b||!b.includeAsr)),function(k){return V2(k)}):[];
case "translationLanguages":return this.i?this.i.u.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.A||void 0==b||w4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.vb&&a.push("stickyLoading");return a};
g.h.Oj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.YM=function(){this.loaded&&this.g&&!q4(this)?(s4(this,"module-enabled",!1),this.unload(),n4(this,!0)&&t4(this,o4(this),!1)):t4(this,q4(this)||!this.g?p4(this,!0):this.g,!0)};
g.h.vI=function(){var a=q4(this);n4(this,a)?t4(this,this.player.getAudioTrack().om,!1):this.O.captionTracks.length&&(this.loaded&&this.unload(),this.Uk()&&(a?t4(this,p4(this),!1):this.load()))};g.IV.captions=l4;})(_yt_player);
